name: scan-actions-max

on:
#    schedule:
#      - cron: '0 0 * * *'
# Remove both comments to run this action on daily basis.
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
          go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
          go get -v github.com/projectdiscovery/httpx/cmd/httpx
          go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
          go get -u github.com/tomnomnom/anew
        shell: bash

      - name: Running Scanner
        run: |
          sudo apt install libpcap-dev
          nuclei -update-templates
          subfinder -silent -dL input/domains.txt -config config/subfinder-config.yaml | anew output/passive_subdomains.txt | naabu -silent | anew output/port.txt | httpx -title -content-length -status-code -silent | anew output/active_urls.txt | nuclei -silent -t cves/ -t default-logins/ -t exposed-panels -t fuzzing -t miscellaneous -t misconfiguration/ -t network -t takeovers -t vulnerabilities/ -t technologies | anew output/nuclei_output.txt
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/passive_subdomains.txt
          git add output/port.txt
          git add output/active_urls.txt
          git add output/nuclei_output.txt

      - name: Commit results to Github
        run: |
          git config --local user.email "xxx@xxx.io"
          git config --global user.name "xxx"
          git commit -m "Scan-Actions report" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
